# Generated by Django 4.2.3 on 2023-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
