# Generated by Django 4.2.3 on 2023-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_animal_alter_person_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
